name = "holstonmeet-production"

account_id = "94bdc287cd4e0622b68f9e18e406ae66"
main = "./build/index.js"
compatibility_date = "2026-06-11"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[kv_namespaces]]
binding = "FEEDBACK_STORAGE"
id = "5359cac2fea240ba9b223c31548b3794"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[vars]
CALLS_APP_ID = "YOUR_CALLS_APP_ID"
TURN_SERVICE_ID = "YOUR_TURN_SERVICE_ID"
EXPERIMENTAL_SIMULCAST_ENABLED = "false"

[[queues.producers]]
 queue = "holstonmeet-feedback-queue"
 binding = "FEEDBACK_QUEUE"

[[queues.consumers]]
 queue = "holstonmeet-feedback-queue"
 max_batch_size = 10
 max_batch_timeout = 5

[[d1_databases]]
binding = "DB"
database_name = "holstonmeet-db-production"
database_id = "b90f95aa-f13a-4fcc-b562-4e9c8db4a8d6"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2"
deleted_classes = ["RateLimiter"]

[observability]
enabled = true
